version: "3"

services:

  runtime-setup:
    image: swift-log:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: swift-log:22.04-main
    environment:
      - FORCE_TEST_DISCOVERY=--enable-test-discovery
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-log:22.04-main
