version: "3"

services:

  runtime-setup:
    image: swift-log:20.04-5.4
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.4-focal"

  test:
    image: swift-log:20.04-5.4
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-log:20.04-5.4
