version: "3"

services:

  runtime-setup:
    image: swift-log:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: swift-log:22.04-main
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      #- SANITIZER_ARG=--sanitize=thread
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - EXPLICIT_SENDABLE_ARG=-Xswiftc -require-explicit-sendable
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: swift-log:22.04-main
