name: codespell
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'
jobs:
  codespell:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Discover typos with codespell
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="hart" --skip="./Pulse/.build/*"
